//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer.InsertDataServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InsertDataServiceReference.IInsertDataService")]
    public interface IInsertDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComputer", ReplyAction="http://tempuri.org/IInsertDataService/InsertComputerResponse")]
        string InsertComputer(
                    string _computerName, 
                    string _operatingSystem, 
                    string _companyFixedAsset, 
                    string _tagService, 
                    string _location, 
                    string _user, 
                    string _office, 
                    string _ip, 
                    string _model, 
                    string _cpu, 
                    string _ram, 
                    string _hardDrive, 
                    string _coments, 
                    System.DateTime purchaseDate, 
                    System.DateTime warrantyDate, 
                    byte[] _barcode, 
                    byte[] _qrCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComputer", ReplyAction="http://tempuri.org/IInsertDataService/InsertComputerResponse")]
        System.Threading.Tasks.Task<string> InsertComputerAsync(
                    string _computerName, 
                    string _operatingSystem, 
                    string _companyFixedAsset, 
                    string _tagService, 
                    string _location, 
                    string _user, 
                    string _office, 
                    string _ip, 
                    string _model, 
                    string _cpu, 
                    string _ram, 
                    string _hardDrive, 
                    string _coments, 
                    System.DateTime purchaseDate, 
                    System.DateTime warrantyDate, 
                    byte[] _barcode, 
                    byte[] _qrCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertNotebooks", ReplyAction="http://tempuri.org/IInsertDataService/InsertNotebooksResponse")]
        string InsertNotebooks(string _notebooksName, string _operatingSystem, string _companyFixedAsset, string _tagService, string _location, string _user, string _office, string _ip, string _model, string _cpu, string _ram, string _hardDrive, string _coments, System.DateTime purchaseDate, System.DateTime warrantyDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertNotebooks", ReplyAction="http://tempuri.org/IInsertDataService/InsertNotebooksResponse")]
        System.Threading.Tasks.Task<string> InsertNotebooksAsync(string _notebooksName, string _operatingSystem, string _companyFixedAsset, string _tagService, string _location, string _user, string _office, string _ip, string _model, string _cpu, string _ram, string _hardDrive, string _coments, System.DateTime purchaseDate, System.DateTime warrantyDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertMonitors", ReplyAction="http://tempuri.org/IInsertDataService/InsertMonitorsResponse")]
        string InsertMonitors(string _companyFixedAsset, string _tagService, string _location, string _user, string _model, string _coments, System.DateTime purchaseDate, System.DateTime warrantyDate, byte[] _barcode, byte[] _qrCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertMonitors", ReplyAction="http://tempuri.org/IInsertDataService/InsertMonitorsResponse")]
        System.Threading.Tasks.Task<string> InsertMonitorsAsync(string _companyFixedAsset, string _tagService, string _location, string _user, string _model, string _coments, System.DateTime purchaseDate, System.DateTime warrantyDate, byte[] _barcode, byte[] _qrCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxCPU", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxCPUResponse")]
        string InsertComboBoxCPU(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxCPU", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxCPUResponse")]
        System.Threading.Tasks.Task<string> InsertComboBoxCPUAsync(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxHardDrive", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxHardDriveResponse")]
        string InsertComboBoxHardDrive(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxHardDrive", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxHardDriveResponse")]
        System.Threading.Tasks.Task<string> InsertComboBoxHardDriveAsync(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxLocation", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxLocationResponse")]
        string InsertComboBoxLocation(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxLocation", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxLocationResponse")]
        System.Threading.Tasks.Task<string> InsertComboBoxLocationAsync(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxMicrosoftOffice", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxMicrosoftOfficeResponse")]
        string InsertComboBoxMicrosoftOffice(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxMicrosoftOffice", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxMicrosoftOfficeResponse")]
        System.Threading.Tasks.Task<string> InsertComboBoxMicrosoftOfficeAsync(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxModelComputer", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxModelComputerResponse")]
        string InsertComboBoxModelComputer(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxModelComputer", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxModelComputerResponse")]
        System.Threading.Tasks.Task<string> InsertComboBoxModelComputerAsync(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxModelMonitor", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxModelMonitorResponse")]
        string InsertComboBoxModelMonitor(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxModelMonitor", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxModelMonitorResponse")]
        System.Threading.Tasks.Task<string> InsertComboBoxModelMonitorAsync(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxModelNotebook", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxModelNotebookResponse")]
        string InsertComboBoxModelNotebook(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxModelNotebook", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxModelNotebookResponse")]
        System.Threading.Tasks.Task<string> InsertComboBoxModelNotebookAsync(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxOperatingSystem", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxOperatingSystemResponse")]
        string InsertComboBoxOperatingSystem(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxOperatingSystem", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxOperatingSystemResponse")]
        System.Threading.Tasks.Task<string> InsertComboBoxOperatingSystemAsync(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxRAM", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxRAMResponse")]
        string InsertComboBoxRAM(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxRAM", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxRAMResponse")]
        System.Threading.Tasks.Task<string> InsertComboBoxRAMAsync(string _value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxUser", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxUserResponse")]
        string InsertComboBoxUser(string _firstName, string _lastName, string _job);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInsertDataService/InsertComboBoxUser", ReplyAction="http://tempuri.org/IInsertDataService/InsertComboBoxUserResponse")]
        System.Threading.Tasks.Task<string> InsertComboBoxUserAsync(string _firstName, string _lastName, string _job);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInsertDataServiceChannel : DataBaseLayer.InsertDataServiceReference.IInsertDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertDataServiceClient : System.ServiceModel.ClientBase<DataBaseLayer.InsertDataServiceReference.IInsertDataService>, DataBaseLayer.InsertDataServiceReference.IInsertDataService {
        
        public InsertDataServiceClient() {
        }
        
        public InsertDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InsertDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsertDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsertDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertComputer(
                    string _computerName, 
                    string _operatingSystem, 
                    string _companyFixedAsset, 
                    string _tagService, 
                    string _location, 
                    string _user, 
                    string _office, 
                    string _ip, 
                    string _model, 
                    string _cpu, 
                    string _ram, 
                    string _hardDrive, 
                    string _coments, 
                    System.DateTime purchaseDate, 
                    System.DateTime warrantyDate, 
                    byte[] _barcode, 
                    byte[] _qrCode) {
            return base.Channel.InsertComputer(_computerName, _operatingSystem, _companyFixedAsset, _tagService, _location, _user, _office, _ip, _model, _cpu, _ram, _hardDrive, _coments, purchaseDate, warrantyDate, _barcode, _qrCode);
        }
        
        public System.Threading.Tasks.Task<string> InsertComputerAsync(
                    string _computerName, 
                    string _operatingSystem, 
                    string _companyFixedAsset, 
                    string _tagService, 
                    string _location, 
                    string _user, 
                    string _office, 
                    string _ip, 
                    string _model, 
                    string _cpu, 
                    string _ram, 
                    string _hardDrive, 
                    string _coments, 
                    System.DateTime purchaseDate, 
                    System.DateTime warrantyDate, 
                    byte[] _barcode, 
                    byte[] _qrCode) {
            return base.Channel.InsertComputerAsync(_computerName, _operatingSystem, _companyFixedAsset, _tagService, _location, _user, _office, _ip, _model, _cpu, _ram, _hardDrive, _coments, purchaseDate, warrantyDate, _barcode, _qrCode);
        }
        
        public string InsertNotebooks(string _notebooksName, string _operatingSystem, string _companyFixedAsset, string _tagService, string _location, string _user, string _office, string _ip, string _model, string _cpu, string _ram, string _hardDrive, string _coments, System.DateTime purchaseDate, System.DateTime warrantyDate) {
            return base.Channel.InsertNotebooks(_notebooksName, _operatingSystem, _companyFixedAsset, _tagService, _location, _user, _office, _ip, _model, _cpu, _ram, _hardDrive, _coments, purchaseDate, warrantyDate);
        }
        
        public System.Threading.Tasks.Task<string> InsertNotebooksAsync(string _notebooksName, string _operatingSystem, string _companyFixedAsset, string _tagService, string _location, string _user, string _office, string _ip, string _model, string _cpu, string _ram, string _hardDrive, string _coments, System.DateTime purchaseDate, System.DateTime warrantyDate) {
            return base.Channel.InsertNotebooksAsync(_notebooksName, _operatingSystem, _companyFixedAsset, _tagService, _location, _user, _office, _ip, _model, _cpu, _ram, _hardDrive, _coments, purchaseDate, warrantyDate);
        }
        
        public string InsertMonitors(string _companyFixedAsset, string _tagService, string _location, string _user, string _model, string _coments, System.DateTime purchaseDate, System.DateTime warrantyDate, byte[] _barcode, byte[] _qrCode) {
            return base.Channel.InsertMonitors(_companyFixedAsset, _tagService, _location, _user, _model, _coments, purchaseDate, warrantyDate, _barcode, _qrCode);
        }
        
        public System.Threading.Tasks.Task<string> InsertMonitorsAsync(string _companyFixedAsset, string _tagService, string _location, string _user, string _model, string _coments, System.DateTime purchaseDate, System.DateTime warrantyDate, byte[] _barcode, byte[] _qrCode) {
            return base.Channel.InsertMonitorsAsync(_companyFixedAsset, _tagService, _location, _user, _model, _coments, purchaseDate, warrantyDate, _barcode, _qrCode);
        }
        
        public string InsertComboBoxCPU(string _value) {
            return base.Channel.InsertComboBoxCPU(_value);
        }
        
        public System.Threading.Tasks.Task<string> InsertComboBoxCPUAsync(string _value) {
            return base.Channel.InsertComboBoxCPUAsync(_value);
        }
        
        public string InsertComboBoxHardDrive(string _value) {
            return base.Channel.InsertComboBoxHardDrive(_value);
        }
        
        public System.Threading.Tasks.Task<string> InsertComboBoxHardDriveAsync(string _value) {
            return base.Channel.InsertComboBoxHardDriveAsync(_value);
        }
        
        public string InsertComboBoxLocation(string _value) {
            return base.Channel.InsertComboBoxLocation(_value);
        }
        
        public System.Threading.Tasks.Task<string> InsertComboBoxLocationAsync(string _value) {
            return base.Channel.InsertComboBoxLocationAsync(_value);
        }
        
        public string InsertComboBoxMicrosoftOffice(string _value) {
            return base.Channel.InsertComboBoxMicrosoftOffice(_value);
        }
        
        public System.Threading.Tasks.Task<string> InsertComboBoxMicrosoftOfficeAsync(string _value) {
            return base.Channel.InsertComboBoxMicrosoftOfficeAsync(_value);
        }
        
        public string InsertComboBoxModelComputer(string _value) {
            return base.Channel.InsertComboBoxModelComputer(_value);
        }
        
        public System.Threading.Tasks.Task<string> InsertComboBoxModelComputerAsync(string _value) {
            return base.Channel.InsertComboBoxModelComputerAsync(_value);
        }
        
        public string InsertComboBoxModelMonitor(string _value) {
            return base.Channel.InsertComboBoxModelMonitor(_value);
        }
        
        public System.Threading.Tasks.Task<string> InsertComboBoxModelMonitorAsync(string _value) {
            return base.Channel.InsertComboBoxModelMonitorAsync(_value);
        }
        
        public string InsertComboBoxModelNotebook(string _value) {
            return base.Channel.InsertComboBoxModelNotebook(_value);
        }
        
        public System.Threading.Tasks.Task<string> InsertComboBoxModelNotebookAsync(string _value) {
            return base.Channel.InsertComboBoxModelNotebookAsync(_value);
        }
        
        public string InsertComboBoxOperatingSystem(string _value) {
            return base.Channel.InsertComboBoxOperatingSystem(_value);
        }
        
        public System.Threading.Tasks.Task<string> InsertComboBoxOperatingSystemAsync(string _value) {
            return base.Channel.InsertComboBoxOperatingSystemAsync(_value);
        }
        
        public string InsertComboBoxRAM(string _value) {
            return base.Channel.InsertComboBoxRAM(_value);
        }
        
        public System.Threading.Tasks.Task<string> InsertComboBoxRAMAsync(string _value) {
            return base.Channel.InsertComboBoxRAMAsync(_value);
        }
        
        public string InsertComboBoxUser(string _firstName, string _lastName, string _job) {
            return base.Channel.InsertComboBoxUser(_firstName, _lastName, _job);
        }
        
        public System.Threading.Tasks.Task<string> InsertComboBoxUserAsync(string _firstName, string _lastName, string _job) {
            return base.Channel.InsertComboBoxUserAsync(_firstName, _lastName, _job);
        }
    }
}
