//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer.DeleteDataServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeleteDataServiceReference.IDeleteDataService")]
    public interface IDeleteDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteDataService/DeleteComputer", ReplyAction="http://tempuri.org/IDeleteDataService/DeleteComputerResponse")]
        string DeleteComputer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteDataService/DeleteComputer", ReplyAction="http://tempuri.org/IDeleteDataService/DeleteComputerResponse")]
        System.Threading.Tasks.Task<string> DeleteComputerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteDataService/DeleteNotebook", ReplyAction="http://tempuri.org/IDeleteDataService/DeleteNotebookResponse")]
        string DeleteNotebook(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteDataService/DeleteNotebook", ReplyAction="http://tempuri.org/IDeleteDataService/DeleteNotebookResponse")]
        System.Threading.Tasks.Task<string> DeleteNotebookAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteDataService/DeleteMonitor", ReplyAction="http://tempuri.org/IDeleteDataService/DeleteMonitorResponse")]
        string DeleteMonitor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteDataService/DeleteMonitor", ReplyAction="http://tempuri.org/IDeleteDataService/DeleteMonitorResponse")]
        System.Threading.Tasks.Task<string> DeleteMonitorAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeleteDataServiceChannel : DataBaseLayer.DeleteDataServiceReference.IDeleteDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteDataServiceClient : System.ServiceModel.ClientBase<DataBaseLayer.DeleteDataServiceReference.IDeleteDataService>, DataBaseLayer.DeleteDataServiceReference.IDeleteDataService {
        
        public DeleteDataServiceClient() {
        }
        
        public DeleteDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeleteDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeleteDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeleteDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DeleteComputer(int id) {
            return base.Channel.DeleteComputer(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteComputerAsync(int id) {
            return base.Channel.DeleteComputerAsync(id);
        }
        
        public string DeleteNotebook(int id) {
            return base.Channel.DeleteNotebook(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteNotebookAsync(int id) {
            return base.Channel.DeleteNotebookAsync(id);
        }
        
        public string DeleteMonitor(int id) {
            return base.Channel.DeleteMonitor(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteMonitorAsync(int id) {
            return base.Channel.DeleteMonitorAsync(id);
        }
    }
}
