//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer.FillComboBoxDataServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FillComboBoxDataServiceReference.IFillComboBoxDataService")]
    public interface IFillComboBoxDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxLocation", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxLocationResponse")]
        string[] FillComboBoxLocation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxLocation", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxLocationResponse")]
        System.Threading.Tasks.Task<string[]> FillComboBoxLocationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxOffice", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxOfficeResponse")]
        string[] FillComboBoxOffice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxOffice", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxOfficeResponse")]
        System.Threading.Tasks.Task<string[]> FillComboBoxOfficeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxOperatingSystem", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxOperatingSystemResponse")]
        string[] FillComboBoxOperatingSystem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxOperatingSystem", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxOperatingSystemResponse")]
        System.Threading.Tasks.Task<string[]> FillComboBoxOperatingSystemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxCPU", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxCPUResponse")]
        string[] FillComboBoxCPU();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxCPU", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxCPUResponse")]
        System.Threading.Tasks.Task<string[]> FillComboBoxCPUAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxHardDrive", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxHardDriveResponse")]
        string[] FillComboBoxHardDrive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxHardDrive", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxHardDriveResponse")]
        System.Threading.Tasks.Task<string[]> FillComboBoxHardDriveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxRAM", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxRAMResponse")]
        string[] FillComboBoxRAM();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxRAM", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxRAMResponse")]
        System.Threading.Tasks.Task<string[]> FillComboBoxRAMAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxModelComputer", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxModelComputerResponse")]
        string[] FillComboBoxModelComputer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxModelComputer", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxModelComputerResponse")]
        System.Threading.Tasks.Task<string[]> FillComboBoxModelComputerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxModelMonitors", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxModelMonitorsResponse")]
        string[] FillComboBoxModelMonitors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxModelMonitors", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxModelMonitorsResponse")]
        System.Threading.Tasks.Task<string[]> FillComboBoxModelMonitorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxModelNotebooks", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxModelNotebooksResponse")]
        string[] FillComboBoxModelNotebooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxModelNotebooks", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxModelNotebooksResponse")]
        System.Threading.Tasks.Task<string[]> FillComboBoxModelNotebooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxUsers", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxUsersResponse")]
        string[] FillComboBoxUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxUsers", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxUsersResponse")]
        System.Threading.Tasks.Task<string[]> FillComboBoxUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxEquipmentStatus", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxEquipmentStatusResponse")]
        string[] FillComboBoxEquipmentStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFillComboBoxDataService/FillComboBoxEquipmentStatus", ReplyAction="http://tempuri.org/IFillComboBoxDataService/FillComboBoxEquipmentStatusResponse")]
        System.Threading.Tasks.Task<string[]> FillComboBoxEquipmentStatusAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFillComboBoxDataServiceChannel : DataBaseLayer.FillComboBoxDataServiceReference.IFillComboBoxDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FillComboBoxDataServiceClient : System.ServiceModel.ClientBase<DataBaseLayer.FillComboBoxDataServiceReference.IFillComboBoxDataService>, DataBaseLayer.FillComboBoxDataServiceReference.IFillComboBoxDataService {
        
        public FillComboBoxDataServiceClient() {
        }
        
        public FillComboBoxDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FillComboBoxDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FillComboBoxDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FillComboBoxDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] FillComboBoxLocation() {
            return base.Channel.FillComboBoxLocation();
        }
        
        public System.Threading.Tasks.Task<string[]> FillComboBoxLocationAsync() {
            return base.Channel.FillComboBoxLocationAsync();
        }
        
        public string[] FillComboBoxOffice() {
            return base.Channel.FillComboBoxOffice();
        }
        
        public System.Threading.Tasks.Task<string[]> FillComboBoxOfficeAsync() {
            return base.Channel.FillComboBoxOfficeAsync();
        }
        
        public string[] FillComboBoxOperatingSystem() {
            return base.Channel.FillComboBoxOperatingSystem();
        }
        
        public System.Threading.Tasks.Task<string[]> FillComboBoxOperatingSystemAsync() {
            return base.Channel.FillComboBoxOperatingSystemAsync();
        }
        
        public string[] FillComboBoxCPU() {
            return base.Channel.FillComboBoxCPU();
        }
        
        public System.Threading.Tasks.Task<string[]> FillComboBoxCPUAsync() {
            return base.Channel.FillComboBoxCPUAsync();
        }
        
        public string[] FillComboBoxHardDrive() {
            return base.Channel.FillComboBoxHardDrive();
        }
        
        public System.Threading.Tasks.Task<string[]> FillComboBoxHardDriveAsync() {
            return base.Channel.FillComboBoxHardDriveAsync();
        }
        
        public string[] FillComboBoxRAM() {
            return base.Channel.FillComboBoxRAM();
        }
        
        public System.Threading.Tasks.Task<string[]> FillComboBoxRAMAsync() {
            return base.Channel.FillComboBoxRAMAsync();
        }
        
        public string[] FillComboBoxModelComputer() {
            return base.Channel.FillComboBoxModelComputer();
        }
        
        public System.Threading.Tasks.Task<string[]> FillComboBoxModelComputerAsync() {
            return base.Channel.FillComboBoxModelComputerAsync();
        }
        
        public string[] FillComboBoxModelMonitors() {
            return base.Channel.FillComboBoxModelMonitors();
        }
        
        public System.Threading.Tasks.Task<string[]> FillComboBoxModelMonitorsAsync() {
            return base.Channel.FillComboBoxModelMonitorsAsync();
        }
        
        public string[] FillComboBoxModelNotebooks() {
            return base.Channel.FillComboBoxModelNotebooks();
        }
        
        public System.Threading.Tasks.Task<string[]> FillComboBoxModelNotebooksAsync() {
            return base.Channel.FillComboBoxModelNotebooksAsync();
        }
        
        public string[] FillComboBoxUsers() {
            return base.Channel.FillComboBoxUsers();
        }
        
        public System.Threading.Tasks.Task<string[]> FillComboBoxUsersAsync() {
            return base.Channel.FillComboBoxUsersAsync();
        }
        
        public string[] FillComboBoxEquipmentStatus() {
            return base.Channel.FillComboBoxEquipmentStatus();
        }
        
        public System.Threading.Tasks.Task<string[]> FillComboBoxEquipmentStatusAsync() {
            return base.Channel.FillComboBoxEquipmentStatusAsync();
        }
    }
}
