//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseLayer.GetDataServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComputersDataView", Namespace="http://schemas.datacontract.org/2004/07/WebServiceHost.Model")]
    [System.SerializableAttribute()]
    public partial class ComputersDataView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPUVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyFixedAssetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HardDriveVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MicrosoftOfficeVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelVersionComputerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatingSystemVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PurchaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RAMVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WarrantyDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeField, value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPUVersion {
            get {
                return this.CPUVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.CPUVersionField, value) != true)) {
                    this.CPUVersionField = value;
                    this.RaisePropertyChanged("CPUVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Coments {
            get {
                return this.ComentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentsField, value) != true)) {
                    this.ComentsField = value;
                    this.RaisePropertyChanged("Coments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyFixedAsset {
            get {
                return this.CompanyFixedAssetField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyFixedAssetField, value) != true)) {
                    this.CompanyFixedAssetField = value;
                    this.RaisePropertyChanged("CompanyFixedAsset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompterName {
            get {
                return this.CompterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompterNameField, value) != true)) {
                    this.CompterNameField = value;
                    this.RaisePropertyChanged("CompterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HardDriveVersion {
            get {
                return this.HardDriveVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.HardDriveVersionField, value) != true)) {
                    this.HardDriveVersionField = value;
                    this.RaisePropertyChanged("HardDriveVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MicrosoftOfficeVersion {
            get {
                return this.MicrosoftOfficeVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.MicrosoftOfficeVersionField, value) != true)) {
                    this.MicrosoftOfficeVersionField = value;
                    this.RaisePropertyChanged("MicrosoftOfficeVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelVersionComputer {
            get {
                return this.ModelVersionComputerField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelVersionComputerField, value) != true)) {
                    this.ModelVersionComputerField = value;
                    this.RaisePropertyChanged("ModelVersionComputer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatingSystemVersion {
            get {
                return this.OperatingSystemVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatingSystemVersionField, value) != true)) {
                    this.OperatingSystemVersionField = value;
                    this.RaisePropertyChanged("OperatingSystemVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PurchaseDate {
            get {
                return this.PurchaseDateField;
            }
            set {
                if ((this.PurchaseDateField.Equals(value) != true)) {
                    this.PurchaseDateField = value;
                    this.RaisePropertyChanged("PurchaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RAMVersion {
            get {
                return this.RAMVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.RAMVersionField, value) != true)) {
                    this.RAMVersionField = value;
                    this.RaisePropertyChanged("RAMVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagService {
            get {
                return this.TagServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.TagServiceField, value) != true)) {
                    this.TagServiceField = value;
                    this.RaisePropertyChanged("TagService");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WarrantyDate {
            get {
                return this.WarrantyDateField;
            }
            set {
                if ((this.WarrantyDateField.Equals(value) != true)) {
                    this.WarrantyDateField = value;
                    this.RaisePropertyChanged("WarrantyDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotebooksDataView", Namespace="http://schemas.datacontract.org/2004/07/WebServiceHost.Model")]
    [System.SerializableAttribute()]
    public partial class NotebooksDataView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPUVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyFixedAssetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HardDriveVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MicrosoftOfficeVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelVersionNotebooksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotebooksNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatingSystemVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PurchaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RAMVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WarrantyDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeField, value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPUVersion {
            get {
                return this.CPUVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.CPUVersionField, value) != true)) {
                    this.CPUVersionField = value;
                    this.RaisePropertyChanged("CPUVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Coments {
            get {
                return this.ComentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentsField, value) != true)) {
                    this.ComentsField = value;
                    this.RaisePropertyChanged("Coments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyFixedAsset {
            get {
                return this.CompanyFixedAssetField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyFixedAssetField, value) != true)) {
                    this.CompanyFixedAssetField = value;
                    this.RaisePropertyChanged("CompanyFixedAsset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HardDriveVersion {
            get {
                return this.HardDriveVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.HardDriveVersionField, value) != true)) {
                    this.HardDriveVersionField = value;
                    this.RaisePropertyChanged("HardDriveVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MicrosoftOfficeVersion {
            get {
                return this.MicrosoftOfficeVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.MicrosoftOfficeVersionField, value) != true)) {
                    this.MicrosoftOfficeVersionField = value;
                    this.RaisePropertyChanged("MicrosoftOfficeVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelVersionNotebooks {
            get {
                return this.ModelVersionNotebooksField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelVersionNotebooksField, value) != true)) {
                    this.ModelVersionNotebooksField = value;
                    this.RaisePropertyChanged("ModelVersionNotebooks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotebooksName {
            get {
                return this.NotebooksNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NotebooksNameField, value) != true)) {
                    this.NotebooksNameField = value;
                    this.RaisePropertyChanged("NotebooksName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatingSystemVersion {
            get {
                return this.OperatingSystemVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatingSystemVersionField, value) != true)) {
                    this.OperatingSystemVersionField = value;
                    this.RaisePropertyChanged("OperatingSystemVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PurchaseDate {
            get {
                return this.PurchaseDateField;
            }
            set {
                if ((this.PurchaseDateField.Equals(value) != true)) {
                    this.PurchaseDateField = value;
                    this.RaisePropertyChanged("PurchaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RAMVersion {
            get {
                return this.RAMVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.RAMVersionField, value) != true)) {
                    this.RAMVersionField = value;
                    this.RaisePropertyChanged("RAMVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagService {
            get {
                return this.TagServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.TagServiceField, value) != true)) {
                    this.TagServiceField = value;
                    this.RaisePropertyChanged("TagService");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WarrantyDate {
            get {
                return this.WarrantyDateField;
            }
            set {
                if ((this.WarrantyDateField.Equals(value) != true)) {
                    this.WarrantyDateField = value;
                    this.RaisePropertyChanged("WarrantyDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonitorsDataView", Namespace="http://schemas.datacontract.org/2004/07/WebServiceHost.Model")]
    [System.SerializableAttribute()]
    public partial class MonitorsDataView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyFixedAssetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelVersionMonitorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PurchaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WarrantyDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Barcode {
            get {
                return this.BarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarcodeField, value) != true)) {
                    this.BarcodeField = value;
                    this.RaisePropertyChanged("Barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Coments {
            get {
                return this.ComentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentsField, value) != true)) {
                    this.ComentsField = value;
                    this.RaisePropertyChanged("Coments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyFixedAsset {
            get {
                return this.CompanyFixedAssetField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyFixedAssetField, value) != true)) {
                    this.CompanyFixedAssetField = value;
                    this.RaisePropertyChanged("CompanyFixedAsset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelVersionMonitors {
            get {
                return this.ModelVersionMonitorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelVersionMonitorsField, value) != true)) {
                    this.ModelVersionMonitorsField = value;
                    this.RaisePropertyChanged("ModelVersionMonitors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PurchaseDate {
            get {
                return this.PurchaseDateField;
            }
            set {
                if ((this.PurchaseDateField.Equals(value) != true)) {
                    this.PurchaseDateField = value;
                    this.RaisePropertyChanged("PurchaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagService {
            get {
                return this.TagServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.TagServiceField, value) != true)) {
                    this.TagServiceField = value;
                    this.RaisePropertyChanged("TagService");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WarrantyDate {
            get {
                return this.WarrantyDateField;
            }
            set {
                if ((this.WarrantyDateField.Equals(value) != true)) {
                    this.WarrantyDateField = value;
                    this.RaisePropertyChanged("WarrantyDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetDataServiceReference.IGetDataService")]
    public interface IGetDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataService/GetAllComputerses", ReplyAction="http://tempuri.org/IGetDataService/GetAllComputersesResponse")]
        DataBaseLayer.GetDataServiceReference.ComputersDataView[] GetAllComputerses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataService/GetAllComputerses", ReplyAction="http://tempuri.org/IGetDataService/GetAllComputersesResponse")]
        System.Threading.Tasks.Task<DataBaseLayer.GetDataServiceReference.ComputersDataView[]> GetAllComputersesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataService/GetAllNotebookses", ReplyAction="http://tempuri.org/IGetDataService/GetAllNotebooksesResponse")]
        DataBaseLayer.GetDataServiceReference.NotebooksDataView[] GetAllNotebookses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataService/GetAllNotebookses", ReplyAction="http://tempuri.org/IGetDataService/GetAllNotebooksesResponse")]
        System.Threading.Tasks.Task<DataBaseLayer.GetDataServiceReference.NotebooksDataView[]> GetAllNotebooksesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataService/GetAllMonitors", ReplyAction="http://tempuri.org/IGetDataService/GetAllMonitorsResponse")]
        DataBaseLayer.GetDataServiceReference.MonitorsDataView[] GetAllMonitors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDataService/GetAllMonitors", ReplyAction="http://tempuri.org/IGetDataService/GetAllMonitorsResponse")]
        System.Threading.Tasks.Task<DataBaseLayer.GetDataServiceReference.MonitorsDataView[]> GetAllMonitorsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetDataServiceChannel : DataBaseLayer.GetDataServiceReference.IGetDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataServiceClient : System.ServiceModel.ClientBase<DataBaseLayer.GetDataServiceReference.IGetDataService>, DataBaseLayer.GetDataServiceReference.IGetDataService {
        
        public GetDataServiceClient() {
        }
        
        public GetDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataBaseLayer.GetDataServiceReference.ComputersDataView[] GetAllComputerses() {
            return base.Channel.GetAllComputerses();
        }
        
        public System.Threading.Tasks.Task<DataBaseLayer.GetDataServiceReference.ComputersDataView[]> GetAllComputersesAsync() {
            return base.Channel.GetAllComputersesAsync();
        }
        
        public DataBaseLayer.GetDataServiceReference.NotebooksDataView[] GetAllNotebookses() {
            return base.Channel.GetAllNotebookses();
        }
        
        public System.Threading.Tasks.Task<DataBaseLayer.GetDataServiceReference.NotebooksDataView[]> GetAllNotebooksesAsync() {
            return base.Channel.GetAllNotebooksesAsync();
        }
        
        public DataBaseLayer.GetDataServiceReference.MonitorsDataView[] GetAllMonitors() {
            return base.Channel.GetAllMonitors();
        }
        
        public System.Threading.Tasks.Task<DataBaseLayer.GetDataServiceReference.MonitorsDataView[]> GetAllMonitorsAsync() {
            return base.Channel.GetAllMonitorsAsync();
        }
    }
}
